# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreTema', models.CharField(max_length=100)),
                ('NombreMateria', models.CharField(max_length=100)),
                ('TextPreg', models.CharField(max_length=200)),
            ],
        ),
    ]
