# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='temas',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='materias.Materia'),
            preserve_default=False,
        ),
    ]
