# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='temas',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='materias.Materia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre_materia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tema',
            name='nombre_tema',
            field=models.CharField(max_length=100),
        ),
    ]
