# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_auto_20161101_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='promedio',
            field=models.IntegerField(default=0),
        ),
    ]
