# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0003_materia_promedio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='promedio',
            field=models.FloatField(default=0),
        ),
    ]
