# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_delete_homepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homepage',
        ),
    ]
