# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_delete_homepage'),
        ('homepage', '0002_auto_20161023_2059'),
    ]

    operations = [
    ]
