# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PregResp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='pregunta_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='preguntas_correctas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='preguntas_incorrectas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pregresp',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenes.Exam'),
        ),
    ]
