# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_reportada'),
        ('examenes', '0002_auto_20161109_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregresp',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
    ]
