# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0002_auto_20161101_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='preguntas_correctas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='preguntas_incorrectas',
            field=models.IntegerField(default=0),
        ),
    ]
