# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0002_auto_20161109_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregresp',
            name='question_id',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
