# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0003_pregresp_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamErrores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tema', models.CharField(max_length=100)),
                ('cantidad_temas', models.IntegerField(default=0)),
                ('nombre_materia', models.CharField(max_length=100)),
                ('tiempo_preg', models.IntegerField(default=0)),
                ('cantidad_preg', models.IntegerField(default=0)),
                ('pregunta_actual', models.IntegerField(default=0)),
                ('preguntas_correctas', models.IntegerField(default=0)),
                ('preguntas_incorrectas', models.IntegerField(default=0)),
            ],
        ),
    ]
