# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_nota_reporte'),
        ('examenes', '0003_pregresp_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregresp',
            name='question_id',
        ),
        migrations.AddField(
            model_name='exam',
            name='porcentaje',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pregresp',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
    ]
