# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0004_auto_20161116_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tema', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='exam',
            name='nombre_tema',
        ),
        migrations.AddField(
            model_name='temae',
            name='tema_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenes.Exam'),
        ),
    ]
