# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0004_examerrores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examerrores',
            name='cantidad_temas',
        ),
    ]
