# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreTema', models.CharField(max_length=50)),
                ('NombreSubtema', models.CharField(max_length=50)),
                ('NombreMateria', models.CharField(max_length=50)),
                ('NumeroPreg', models.IntegerField()),
                ('ValorPreg', models.IntegerField()),
                ('TextPreg', models.CharField(max_length=200)),
                ('Reportada', models.BooleanField(default=False)),
            ],
        ),
    ]
