# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reportada',
            field=models.BooleanField(default=False),
        ),
    ]
