# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_reportada'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='nota_reporte',
            field=models.CharField(default=14, max_length=200),
            preserve_default=False,
        ),
    ]
