# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questionsreportada'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionsReportada',
            new_name='ReportedQuestion',
        ),
    ]
